# Generated by Django 3.1.3 on 2020-11-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegobbyblog', '0006_auto_20201130_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above to Read Blog Post...', max_length=255),
        ),
    ]
